baseurl = "https://github.com/sethmacleod/dimension.git"
title = "Simple."
theme = "dimension"
 languageCode = "en-us"
  defaultContentLanguage = "en-us"
  enableRobotsTXT = true
disableKinds=["RSS"]
  
  [params]
    description = '<!--[-->Simple meaning. Simple design. Simple Shirts.<!--]--><br />
                  <!--[-->Produced by M&C.<!--]-->'
    logo = "fa-diamond"
  [languages.en]
  languageName = "English"
  weight = 1

  [languages.de]
  languageName = "English"